export const tokenAllocationData = [
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "A",
    Project: "Connext",
    "": "30",
    "Public Presale": "0",
    "Private Investors": "30",
    Community: "50",
    __1: "50",
    __2: "",
    Team: "20",
    "Treasury / Foundations": "0",
    Total: "100",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "Derivatives",
    "Project Name": "B",
    Project: "Rally",
    "": "15",
    "Public Presale": "0",
    "Private Investors": "15",
    Community: "50",
    __1: "50",
    __2: "",
    Team: "14",
    "Treasury / Foundations": "20",
    Total: "100",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "C",
    Project: "Uniswap",
    "": "18",
    "Public Presale": "0",
    "Private Investors": "18",
    Community: "60",
    __1: "45",
    __2: "15",
    Team: "21",
    "Treasury / Foundations": "1",
    Total: "100",
  },
  {
    Blockchain: "Polygon",
    Sector: "DEFI",
    "Sub-sector": "Derivatives",
    "Project Name": "D",
    Project: "SKALE internal",
    "": "28",
    "Public Presale": "28",
    "Private Investors": "0",
    Community: "33",
    __1: "33",
    __2: "",
    Team: "20",
    "Treasury / Foundations": "19",
    Total: "100",
  },
  {
    Blockchain: "Polygon",
    Sector: "DEFI",
    "Sub-sector": "Asset Management",
    "Project Name": "E",
    Project: "Flow",
    "": "12",
    "Public Presale": "12",
    "Private Investors": "0",
    Community: "30",
    __1: "30",
    __2: "",
    Team: "58",
    "Treasury / Foundations": "0",
    Total: "100",
  },
  {
    Blockchain: "Solana",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "F",
    Project: "Solana",
    "": "3",
    "Public Presale": "3",
    "Private Investors": "0",
    Community: "30",
    __1: "30",
    __2: "",
    Team: "48",
    "Treasury / Foundations": "19",
    Total: "100",
  },
  {
    Blockchain: "Polygon",
    Sector: "DEFI",
    "Sub-sector": "Lending",
    "Project Name": "G",
    Project: "UMA",
    "": "17",
    "Public Presale": "17",
    "Private Investors": "0",
    Community: "25",
    __1: "25",
    __2: "",
    Team: "49",
    "Treasury / Foundations": "10",
    Total: "100",
  },
  {
    Blockchain: "Polygon",
    Sector: "NFT",
    "Sub-sector": "Collectibles",
    "Project Name": "H",
    Project: "Nervos",
    "": "33",
    "Public Presale": "33",
    "Private Investors": "0",
    Community: "22",
    __1: "22",
    __2: "",
    Team: "45",
    "Treasury / Foundations": "0",
    Total: "100",
  },
  {
    Blockchain: "Solana",
    Sector: "DEFI",
    "Sub-sector": "Lending",
    "Project Name": "I",
    Project: "Celo",
    "": "3",
    "Public Presale": "3",
    "Private Investors": "0",
    Community: "15",
    __1: "15",
    __2: "",
    Team: "44",
    "Treasury / Foundations": "38",
    Total: "100",
  },
  {
    Blockchain: "Avalanche",
    Sector: "NFT",
    "Sub-sector": "Sports",
    "Project Name": "E",
    Project: "Avalance",
    "": "18",
    "Public Presale": "18",
    "Private Investors": "0",
    Community: "15",
    __1: "15",
    __2: "",
    Team: "42",
    "Treasury / Foundations": "25",
    Total: "100",
  },
  {
    Blockchain: "Avalanche",
    Sector: "DEFI",
    "Sub-sector": "Lending",
    "Project Name": "F",
    Project: "SKALE Messari",
    "": "8",
    "Public Presale": "8",
    "Private Investors": "0",
    Community: "14",
    __1: "14",
    __2: "",
    Team: "67",
    "Treasury / Foundations": "11",
    Total: "100",
  },
  {
    Blockchain: "Avalanche",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "G",
    Project: "The Graph",
    "": "38",
    "Public Presale": "4",
    "Private Investors": "34",
    Community: "11",
    __1: "11",
    __2: "",
    Team: "23",
    "Treasury / Foundations": "28",
    Total: "100",
  },
  {
    Blockchain: "Solana",
    Sector: "NFT",
    "Sub-sector": "Collectibles",
    "Project Name": "H",
    Project: "Nucypher",
    "": "20",
    "Public Presale": "20",
    "Private Investors": "0",
    Community: "10",
    __1: "10",
    __2: "",
    Team: "70",
    "Treasury / Foundations": "0",
    Total: "100",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "Asset Management",
    "Project Name": "I",
    Project: "Qtum",
    "": "0",
    "Public Presale": "0",
    "Private Investors": "0",
    Community: "75",
    __1: "10",
    __2: "65",
    Team: "15",
    "Treasury / Foundations": "10",
    Total: "100",
  },
  {
    Blockchain: "Solana",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "E",
    Project: "Kadena",
    "": "3",
    "Public Presale": "3",
    "Private Investors": "0",
    Community: "5",
    __1: "5",
    __2: "",
    Team: "23",
    "Treasury / Foundations": "69",
    Total: "100",
  },
  {
    Blockchain: "Ethereum",
    Sector: "NFT",
    "Sub-sector": "Gaming",
    "Project Name": "F",
    Project: "Edgeware",
    "": "87",
    "Public Presale": "87",
    "Private Investors": "0",
    Community: "5",
    __1: "5",
    __2: "",
    Team: "8",
    "Treasury / Foundations": "0",
    Total: "100",
  },
  {
    Blockchain: "Ethereum",
    Sector: "NFT",
    "Sub-sector": "Gaming",
    "Project Name": "G",
    Project: "Blockstack",
    "": "25",
    "Public Presale": "25",
    "Private Investors": "0",
    Community: "0",
    __1: "0",
    __2: "",
    Team: "41",
    "Treasury / Foundations": "34",
    Total: "100",
  },
  {
    Blockchain: "Ethereum",
    Sector: "NFT",
    "Sub-sector": "Gaming",
    "Project Name": "H",
    Project: "Polkadot",
    "": "52",
    "Public Presale": "52",
    "Private Investors": "0",
    Community: "0",
    __1: "0",
    __2: "",
    Team: "35",
    "Treasury / Foundations": "13",
    Total: "100",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "I",
    Project: "Ignis",
    "": "44",
    "Public Presale": "44",
    "Private Investors": "0",
    Community: "50",
    __1: "",
    __2: "50",
    Team: "6",
    "Treasury / Foundations": "0",
    Total: "100",
  },
];

function cleanData(data) {
  return data.map((allocation) => ({
    blockchain: allocation.Blockchain,
    sector: allocation.Sector,
    subSector: allocation["Sub-sector"],
    projectName: allocation["Project Name"],
    presale: parseInt(allocation["Public Presale"], 10),
    privateInvestors: parseInt(allocation["Private Investors"], 10),
    community: parseInt(allocation.Community, 10),
    team: parseInt(allocation.Team, 10),
  }));
}

export const cleanedAllocations = cleanData(tokenAllocationData);