export const tokenAllocationData = [
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "A",
    Project: "Connext",
    Community: "50%",
    Team: "20%",
    "Treasury / Foundations": "0%",
    Total: "100%",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "Derivatives",
    "Project Name": "B",
    Project: "Rally",
    Community: "50%",
    Team: "14%",
    "Treasury / Foundations": "20%",
    Total: "100%",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "C",
    Project: "Uniswap",
    Community: "60%",
    Team: "21%",
    "Treasury / Foundations": "1%",
    Total: "100%",
  },
  {
    Blockchain: "Polygon",
    Sector: "DEFI",
    "Sub-sector": "Derivatives",
    "Project Name": "D",
    Project: "SKALE internal",
    Community: "33%",
    Team: "20%",
    "Treasury / Foundations": "19%",
    Total: "100%",
  },
  {
    Blockchain: "Polygon",
    Sector: "DEFI",
    "Sub-sector": "Asset Management",
    "Project Name": "E",
    Project: "Flow",
    Community: "30%",
    Team: "58%",
    "Treasury / Foundations": "0%",
    Total: "100%",
  },
  {
    Blockchain: "Solana",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "F",
    Project: "Solana",
    Community: "30%",
    Team: "48%",
    "Treasury / Foundations": "19%",
    Total: "100%",
  },
  {
    Blockchain: "Polygon",
    Sector: "DEFI",
    "Sub-sector": "Lending",
    "Project Name": "G",
    Project: "UMA",
    Community: "25%",
    Team: "49%",
    "Treasury / Foundations": "10%",
    Total: "100%",
  },
  {
    Blockchain: "Polygon",
    Sector: "NFT",
    "Sub-sector": "Collectibles",
    "Project Name": "H",
    Project: "Nervos",
    Community: "22%",
    Team: "45%",
    "Treasury / Foundations": "0%",
    Total: "100%",
  },
  {
    Blockchain: "Solana",
    Sector: "DEFI",
    "Sub-sector": "Lending",
    "Project Name": "I",
    Project: "Celo",
    Community: "15%",
    Team: "44%",
    "Treasury / Foundations": "38%",
    Total: "100%",
  },
  {
    Blockchain: "Avalanche",
    Sector: "NFT",
    "Sub-sector": "Sports",
    "Project Name": "E",
    Project: "Avalance",
    Community: "15%",
    Team: "42%",
    "Treasury / Foundations": "25%",
    Total: "100%",
  },
  {
    Blockchain: "Avalanche",
    Sector: "DEFI",
    "Sub-sector": "Lending",
    "Project Name": "F",
    Project: "SKALE Messari",
    Community: "14%",
    Team: "67%",
    "Treasury / Foundations": "11%",
    Total: "100%",
  },
  {
    Blockchain: "Avalanche",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "G",
    Project: "The Graph",
    Community: "11%",
    Team: "23%",
    "Treasury / Foundations": "28%",
    Total: "100%",
  },
  {
    Blockchain: "Solana",
    Sector: "NFT",
    "Sub-sector": "Collectibles",
    "Project Name": "H",
    Project: "Nucypher",
    Community: "10%",
    Team: "70%",
    "Treasury / Foundations": "0%",
    Total: "100%",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "Asset Management",
    "Project Name": "I",
    Project: "Qtum",
    Community: "75%",
    Team: "15%",
    "Treasury / Foundations": "10%",
    Total: "100%",
  },
  {
    Blockchain: "Solana",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "E",
    Project: "Kadena",
    Community: "5%",
    Team: "23%",
    "Treasury / Foundations": "69%",
    Total: "100%",
  },
  {
    Blockchain: "Ethereum",
    Sector: "NFT",
    "Sub-sector": "Gaming",
    "Project Name": "F",
    Project: "Edgeware",
    Community: "5%",
    Team: "8%",
    "Treasury / Foundations": "0%",
    Total: "100%",
  },
  {
    Blockchain: "Ethereum",
    Sector: "NFT",
    "Sub-sector": "Gaming",
    "Project Name": "G",
    Project: "Blockstack",
    Community: "0%",
    Team: "41%",
    "Treasury / Foundations": "34%",
    Total: "100%",
  },
  {
    Blockchain: "Ethereum",
    Sector: "NFT",
    "Sub-sector": "Gaming",
    "Project Name": "H",
    Project: "Polkadot",
    Community: "0%",
    Team: "35%",
    "Treasury / Foundations": "13%",
    Total: "100%",
  },
  {
    Blockchain: "Ethereum",
    Sector: "DEFI",
    "Sub-sector": "DEX",
    "Project Name": "I",
    Project: "Ignis",
    Community: "50%",
    Team: "6%",
    "Treasury / Foundations": "0%",
    Total: "100%",
  },
  {
    Blockchain: "",
    Sector: "",
    "Sub-sector": "",
    "Project Name": "Medium",
    Project: "Median",
    Community: "65%",
    Team: "35%",
    "Treasury / Foundations": "11%",
    Total: "100%",
  },
  {
    Blockchain: "",
    Sector: "",
    "Sub-sector": "",
    "Project Name": "Average",
    Project: "",
    Community: "26%",
    Team: "34%",
    "Treasury / Foundations": "16%",
    Total: "100%",
  },
];
